### ISSUE TITLE
Reduce php requires YouTrack-client library v1.2.1 to php 5.4

### ISSUE THREAD

**Issue by stingmu** [nepda/youtrack#18]
Is it possible to reduce the requirement of php to version 5.4? 
I can't find in your code any problems with php 5.4. 
Thanks!

**Comment by nepda** [comment]
I'm looking into it.

**Comment by nepda** [comment]
So, thats currently not possible without changing a bit of code. See the failing Travis CI test: https://travis-ci.org/nepda/youtrack/jobs/107767450. You're welcome to fork the repo and make a pull request with passing tests. In this case you need to change only one line...

**Comment by Angerslave** [comment]
@nepda do you really need to downgrade phpunit and phpinvoker? Check out travis log for master branch forced to be run with PHP 5.4:
https://travis-ci.org/Angerslave/youtrack/jobs/107752195

Actually I've been running the library on PHP 5.5.9 for half a year already without any issues. I think the issue Travis shows was fixed in this commit:
https://github.com/nepda/youtrack/commit/b30e8c53995083f9712db5b8473b8ee766caafa1
It used syntax sugar from PHP 5.6 in array declaration and it was reverted in the commit. I'm really interested in getting PHP 5.5 (at least) back, because I'm integrating the library into a Drupal module and Drupal's requirement is PHP 5.5.9, I can't force others to install PHP 5.6.

**Comment by stingmu** [comment]
+1 
PHP 5.5 used by over half of users!!! 50.68% !!!
https://seld.be/notes/php-versions-stats-2015-edition

**Comment by Angerslave** [comment]
Power of Open Source
Pull Request - #19
It actually uses ::class magic constant from PHP 5.5, I changed it to direct class name and now we're fine with PHP 5.4 I guess.

**Comment by nepda** [comment]
#19 is merged, version 1.2.2 is released. I hope this will fix it. Thanks @Angerslave for the PR.

**Comment by Angerslave** [comment]
Thanks @nepda for such a quick reply, now I can get back to my module!
